export const demoSeed = {
  "0237-ictve-curso-2025-26": {
    "tipo": "curso",
    "df_al": [
      {
        "ID": "AN01",
        "Estado": "Alta",
        "Apellidos": "Bennani",
        "Nombre": "Omar",
        "Edad": 17,
        "Nacimiento": "23/05/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "obennani20@gmail.com",
        "Movil": "630 095 741"
      },
      {
        "ID": "AN02",
        "Estado": "Alta",
        "Apellidos": "Castro",
        "Nombre": "Valentina",
        "Edad": 18,
        "Nacimiento": "18/10/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "vcastro21@gmail.com",
        "Movil": "693 987 299"
      },
      {
        "ID": "AN03",
        "Estado": "Alta",
        "Apellidos": "Domínguez",
        "Nombre": "Alba",
        "Edad": 24,
        "Nacimiento": "03/08/2002",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "adominguez31@gmail.com",
        "Movil": "636 326 261"
      },
      {
        "ID": "AN04",
        "Estado": "Alta",
        "Apellidos": "Díaz",
        "Nombre": "David",
        "Edad": 17,
        "Nacimiento": "06/02/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "ddiaz13@gmail.com",
        "Movil": "697 411 784"
      },
      {
        "ID": "AN05",
        "Estado": "Alta",
        "Apellidos": "El Amrani",
        "Nombre": "Youssef",
        "Edad": 18,
        "Nacimiento": "16/03/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "yel33@gmail.com",
        "Movil": "611 836 614"
      },
      {
        "ID": "AN06",
        "Estado": "Alta",
        "Apellidos": "El Fassi",
        "Nombre": "Fátima",
        "Edad": 18,
        "Nacimiento": "01/03/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "fel76@gmail.com",
        "Movil": "625 252 575"
      },
      {
        "ID": "AN07",
        "Estado": "Alta",
        "Apellidos": "Fernández",
        "Nombre": "Daniel",
        "Edad": 20,
        "Nacimiento": "13/04/2006",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "dfernandez55@gmail.com",
        "Movil": "649 761 012"
      },
      {
        "ID": "AN08",
        "Estado": "Alta",
        "Apellidos": "García",
        "Nombre": "Mario",
        "Edad": 20,
        "Nacimiento": "17/10/2006",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "mgarcia18@gmail.com",
        "Movil": "682 217 804"
      },
      {
        "ID": "AN09",
        "Estado": "Alta",
        "Apellidos": "Gómez",
        "Nombre": "Alejandro",
        "Edad": 17,
        "Nacimiento": "09/11/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "agomez73@gmail.com",
        "Movil": "621 908 720"
      },
      {
        "ID": "AN10",
        "Estado": "Baja",
        "Apellidos": "Gómez",
        "Nombre": "Martina",
        "Edad": 19,
        "Nacimiento": "05/08/2007",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "mgomez81@gmail.com",
        "Movil": "631 800 049"
      },
      {
        "ID": "AN11",
        "Estado": "Alta",
        "Apellidos": "Ionescu",
        "Nombre": "Elena",
        "Edad": 19,
        "Nacimiento": "29/10/2007",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "eionescu34@gmail.com",
        "Movil": "646 346 566"
      },
      {
        "ID": "AN12",
        "Estado": "Baja",
        "Apellidos": "López",
        "Nombre": "Javier",
        "Edad": 22,
        "Nacimiento": "28/11/2004",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "jlopez60@gmail.com",
        "Movil": "668 104 985"
      },
      {
        "ID": "AN13",
        "Estado": "Alta",
        "Apellidos": "Martín",
        "Nombre": "Lucía",
        "Edad": 17,
        "Nacimiento": "21/03/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "lmartin23@gmail.com",
        "Movil": "670 585 709"
      },
      {
        "ID": "AN14",
        "Estado": "Alta",
        "Apellidos": "Martínez",
        "Nombre": "Hugo",
        "Edad": 17,
        "Nacimiento": "24/02/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "hmartinez89@gmail.com",
        "Movil": "674 670 543"
      },
      {
        "ID": "AN15",
        "Estado": "Alta",
        "Apellidos": "Mendoza",
        "Nombre": "Diego",
        "Edad": 18,
        "Nacimiento": "27/10/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "dmendoza82@gmail.com",
        "Movil": "697 868 020"
      },
      {
        "ID": "AN16",
        "Estado": "Alta",
        "Apellidos": "Navarro",
        "Nombre": "Laura",
        "Edad": 17,
        "Nacimiento": "04/01/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "lnavarro52@gmail.com",
        "Movil": "634 422 081"
      },
      {
        "ID": "AN17",
        "Estado": "Alta",
        "Apellidos": "Ortiz",
        "Nombre": "Sofía",
        "Edad": 20,
        "Nacimiento": "10/01/2006",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "sortiz55@gmail.com",
        "Movil": "649 489 747"
      },
      {
        "ID": "AN18",
        "Estado": "Alta",
        "Apellidos": "Popescu",
        "Nombre": "Vlad",
        "Edad": 17,
        "Nacimiento": "19/08/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "vpopescu75@gmail.com",
        "Movil": "659 883 473"
      },
      {
        "ID": "AN19",
        "Estado": "Alta",
        "Apellidos": "Pérez",
        "Nombre": "Carlos",
        "Edad": 18,
        "Nacimiento": "30/03/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "cperez11@gmail.com",
        "Movil": "610 318 038"
      },
      {
        "ID": "AN20",
        "Estado": "Alta",
        "Apellidos": "Radu",
        "Nombre": "Andrei",
        "Edad": 17,
        "Nacimiento": "24/07/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "aradu37@gmail.com",
        "Movil": "660 083 751"
      },
      {
        "ID": "AN21",
        "Estado": "Alta",
        "Apellidos": "Ramos",
        "Nombre": "Paula",
        "Edad": 25,
        "Nacimiento": "14/06/2001",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "pramos34@gmail.com",
        "Movil": "610 134 509"
      },
      {
        "ID": "AN22",
        "Estado": "Alta",
        "Apellidos": "Ruiz",
        "Nombre": "Marcos",
        "Edad": 17,
        "Nacimiento": "14/10/2009",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "mruiz61@gmail.com",
        "Movil": "611 873 500"
      },
      {
        "ID": "AN23",
        "Estado": "Alta",
        "Apellidos": "Sánchez",
        "Nombre": "Pablo",
        "Edad": 18,
        "Nacimiento": "25/03/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "psanchez60@gmail.com",
        "Movil": "616 882 201"
      },
      {
        "ID": "AN24",
        "Estado": "Alta",
        "Apellidos": "Vargas",
        "Nombre": "Mateo",
        "Edad": 18,
        "Nacimiento": "14/01/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "mvargas13@gmail.com",
        "Movil": "657 885 202"
      },
      {
        "ID": "AN25",
        "Estado": "Alta",
        "Apellidos": "Álvarez",
        "Nombre": "Sergio",
        "Edad": 18,
        "Nacimiento": "15/04/2008",
        "Repite": "No",
        "Matricula": "",
        "Comentarios": "",
        "email": "salvarez87@gmail.com",
        "Movil": "699 764 564"
      }
    ],
    "df_eval": [
      {
        "ID": "AN01",
        "1T_Teoria": 2.7,
        "1T_Practica": 3.0,
        "1T_Informes": 4.0,
        "1T_Cuaderno": 4.2,
        "1T_Nota": 3.47,
        "2T_Teoria": 2.9,
        "2T_Practica": 2.1,
        "2T_Informes": 4.2,
        "2T_Cuaderno": 4.1,
        "2T_Nota": 3.36,
        "3T_Teoria": 5.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 1.5,
        "Nota_Final": 10.0,
        "ACT01": 10.0,
        "ACT02": 10.0,
        "ACT03": 10.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN02",
        "1T_Teoria": 4.1,
        "1T_Practica": 6.0,
        "1T_Informes": 6.5,
        "1T_Cuaderno": 7.1,
        "1T_Nota": 5.86,
        "2T_Teoria": 5.8,
        "2T_Practica": 6.1,
        "2T_Informes": 7.0,
        "2T_Cuaderno": 7.8,
        "2T_Nota": 6.7,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN03",
        "1T_Teoria": 6.4,
        "1T_Practica": 7.0,
        "1T_Informes": 9.7,
        "1T_Cuaderno": 9.8,
        "1T_Nota": 8.2,
        "2T_Teoria": 7.0,
        "2T_Practica": 8.0,
        "2T_Informes": 10.0,
        "2T_Cuaderno": 10.0,
        "2T_Nota": 8.7,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN04",
        "1T_Teoria": 3.2,
        "1T_Practica": 3.5,
        "1T_Informes": 2.5,
        "1T_Cuaderno": 5.5,
        "1T_Nota": 3.81,
        "2T_Teoria": 2.4,
        "2T_Practica": 3.2,
        "2T_Informes": 2.8,
        "2T_Cuaderno": 5.1,
        "2T_Nota": 3.45,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN05",
        "1T_Teoria": 2.2,
        "1T_Practica": 2.8,
        "1T_Informes": 4.0,
        "1T_Cuaderno": 4.1,
        "1T_Nota": 3.25,
        "2T_Teoria": 2.1,
        "2T_Practica": 4.3,
        "2T_Informes": 4.0,
        "2T_Cuaderno": 4.1,
        "2T_Nota": 3.52,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN06",
        "1T_Teoria": 3.0,
        "1T_Practica": 2.8,
        "1T_Informes": 3.6,
        "1T_Cuaderno": 3.3,
        "1T_Nota": 3.17,
        "2T_Teoria": 3.1,
        "2T_Practica": 4.7,
        "2T_Informes": 4.1,
        "2T_Cuaderno": 4.5,
        "2T_Nota": 4.04,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN07",
        "1T_Teoria": 1.9,
        "1T_Practica": 4.0,
        "1T_Informes": 3.0,
        "1T_Cuaderno": 3.1,
        "1T_Nota": 2.9,
        "2T_Teoria": 2.8,
        "2T_Practica": 3.9,
        "2T_Informes": 3.9,
        "2T_Cuaderno": 3.0,
        "2T_Nota": 3.3,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN08",
        "1T_Teoria": 1.8,
        "1T_Practica": 4.3,
        "1T_Informes": 4.3,
        "1T_Cuaderno": 4.5,
        "1T_Nota": 3.61,
        "2T_Teoria": 3.3,
        "2T_Practica": 3.5,
        "2T_Informes": 2.7,
        "2T_Cuaderno": 4.1,
        "2T_Nota": 3.46,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN09",
        "1T_Teoria": 2.0,
        "1T_Practica": 2.4,
        "1T_Informes": 4.1,
        "1T_Cuaderno": 4.1,
        "1T_Nota": 3.13,
        "2T_Teoria": 1.2,
        "2T_Practica": 3.3,
        "2T_Informes": 4.1,
        "2T_Cuaderno": 4.5,
        "2T_Nota": 3.19,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN10",
        "1T_Teoria": 1.3,
        "1T_Practica": 2.6,
        "1T_Informes": 4.9,
        "1T_Cuaderno": 3.9,
        "1T_Nota": 3.06,
        "2T_Teoria": 4.0,
        "2T_Practica": 3.7,
        "2T_Informes": 3.8,
        "2T_Cuaderno": 5.5,
        "2T_Nota": 4.35,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 0.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN11",
        "1T_Teoria": 6.2,
        "1T_Practica": 6.5,
        "1T_Informes": 9.3,
        "1T_Cuaderno": 9.9,
        "1T_Nota": 7.99,
        "2T_Teoria": 7.4,
        "2T_Practica": 7.7,
        "2T_Informes": 9.4,
        "2T_Cuaderno": 9.7,
        "2T_Nota": 8.55,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN12",
        "1T_Teoria": 4.6,
        "1T_Practica": 7.2,
        "1T_Informes": 6.4,
        "1T_Cuaderno": 6.6,
        "1T_Nota": 6.08,
        "2T_Teoria": 4.2,
        "2T_Practica": 7.3,
        "2T_Informes": 6.2,
        "2T_Cuaderno": 7.3,
        "2T_Nota": 6.15,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.95,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN13",
        "1T_Teoria": 4.2,
        "1T_Practica": 7.5,
        "1T_Informes": 6.8,
        "1T_Cuaderno": 6.6,
        "1T_Nota": 6.1,
        "2T_Teoria": 5.5,
        "2T_Practica": 7.5,
        "2T_Informes": 6.8,
        "2T_Cuaderno": 7.1,
        "2T_Nota": 6.64,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN14",
        "1T_Teoria": 2.1,
        "1T_Practica": 3.8,
        "1T_Informes": 2.1,
        "1T_Cuaderno": 3.4,
        "1T_Nota": 2.83,
        "2T_Teoria": 2.3,
        "2T_Practica": 4.4,
        "2T_Informes": 2.7,
        "2T_Cuaderno": 5.3,
        "2T_Nota": 3.7,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN15",
        "1T_Teoria": 1.3,
        "1T_Practica": 2.6,
        "1T_Informes": 2.6,
        "1T_Cuaderno": 5.0,
        "1T_Nota": 2.93,
        "2T_Teoria": 1.8,
        "2T_Practica": 3.5,
        "2T_Informes": 2.8,
        "2T_Cuaderno": 3.7,
        "2T_Nota": 2.91,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN16",
        "1T_Teoria": 3.3,
        "1T_Practica": 4.0,
        "1T_Informes": 3.6,
        "1T_Cuaderno": 3.0,
        "1T_Nota": 3.41,
        "2T_Teoria": 2.7,
        "2T_Practica": 3.2,
        "2T_Informes": 2.9,
        "2T_Cuaderno": 5.7,
        "2T_Nota": 3.74,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN17",
        "1T_Teoria": 2.4,
        "1T_Practica": 2.4,
        "1T_Informes": 2.4,
        "1T_Cuaderno": 5.3,
        "1T_Nota": 3.27,
        "2T_Teoria": 2.4,
        "2T_Practica": 3.8,
        "2T_Informes": 2.9,
        "2T_Cuaderno": 4.3,
        "2T_Nota": 3.35,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN18",
        "1T_Teoria": 5.2,
        "1T_Practica": 5.9,
        "1T_Informes": 6.2,
        "1T_Cuaderno": 7.5,
        "1T_Nota": 6.23,
        "2T_Teoria": 5.3,
        "2T_Practica": 6.9,
        "2T_Informes": 6.9,
        "2T_Cuaderno": 7.0,
        "2T_Nota": 6.45,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN19",
        "1T_Teoria": 2.6,
        "1T_Practica": 3.7,
        "1T_Informes": 3.4,
        "1T_Cuaderno": 4.9,
        "1T_Nota": 3.67,
        "2T_Teoria": 2.4,
        "2T_Practica": 3.0,
        "2T_Informes": 3.6,
        "2T_Cuaderno": 3.9,
        "2T_Nota": 3.21,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN20",
        "1T_Teoria": 1.5,
        "1T_Practica": 3.6,
        "1T_Informes": 4.7,
        "1T_Cuaderno": 3.1,
        "1T_Nota": 3.04,
        "2T_Teoria": 2.3,
        "2T_Practica": 3.9,
        "2T_Informes": 3.6,
        "2T_Cuaderno": 4.7,
        "2T_Nota": 3.6,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN21",
        "1T_Teoria": 5.0,
        "1T_Practica": 7.0,
        "1T_Informes": 7.0,
        "1T_Cuaderno": 7.9,
        "1T_Nota": 6.67,
        "2T_Teoria": 5.2,
        "2T_Practica": 7.0,
        "2T_Informes": 6.5,
        "2T_Cuaderno": 7.4,
        "2T_Nota": 6.48,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN22",
        "1T_Teoria": 1.5,
        "1T_Practica": 3.3,
        "1T_Informes": 4.2,
        "1T_Cuaderno": 4.7,
        "1T_Nota": 3.36,
        "2T_Teoria": 2.5,
        "2T_Practica": 3.9,
        "2T_Informes": 4.4,
        "2T_Cuaderno": 4.0,
        "2T_Nota": 3.61,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN23",
        "1T_Teoria": 7.3,
        "1T_Practica": 6.7,
        "1T_Informes": 9.4,
        "1T_Cuaderno": 10.0,
        "1T_Nota": 8.41,
        "2T_Teoria": 7.6,
        "2T_Practica": 7.7,
        "2T_Informes": 10.0,
        "2T_Cuaderno": 10.0,
        "2T_Nota": 8.82,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN24",
        "1T_Teoria": 1.3,
        "1T_Practica": 3.3,
        "1T_Informes": 2.4,
        "1T_Cuaderno": 3.5,
        "1T_Nota": 2.58,
        "2T_Teoria": 3.5,
        "2T_Practica": 2.9,
        "2T_Informes": 4.9,
        "2T_Cuaderno": 5.1,
        "2T_Nota": 4.14,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      },
      {
        "ID": "AN25",
        "1T_Teoria": 4.0,
        "1T_Practica": 7.0,
        "1T_Informes": 6.8,
        "1T_Cuaderno": 6.5,
        "1T_Nota": 5.91,
        "2T_Teoria": 5.6,
        "2T_Practica": 5.9,
        "2T_Informes": 7.9,
        "2T_Cuaderno": 6.6,
        "2T_Nota": 6.42,
        "3T_Teoria": 0.0,
        "3T_Practica": 0,
        "3T_Informes": 0,
        "3T_Cuaderno": 0,
        "3T_Nota": 0.0,
        "Nota_Final": 1.0,
        "ACT01": 0.0,
        "ACT02": 0.0,
        "ACT03": 0.0,
        "ACT04": 0.0,
        "ACT05": 0.0,
        "ACT06": 0.0,
        "ACT07": 0.0,
        "ACT08": 0.0,
        "ACT09": 0.0,
        "ACT10": 0.0,
        "ACT11": 0.0,
        "ACT12": 0.0
      }
    ],
    "df_feoe": [],
    "df_sgmt": [
      {
        "id_ud": "UD01",
        "horas_ud": 25,
        "Sep_Prv": 11,
        "Sep_Imp": 11,
        "Oct_Prv": 14,
        "Oct_Imp": 13,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD02",
        "horas_ud": 30,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 2,
        "Oct_Imp": 2,
        "Nov_Prv": 15,
        "Nov_Imp": 15,
        "Dic_Prv": 11,
        "Dic_Imp": 11,
        "Ene_Prv": 2,
        "Ene_Imp": 2,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD03",
        "horas_ud": 15,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 10,
        "Ene_Imp": 10,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 5,
        "Mar_Imp": 5,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD04",
        "horas_ud": 10,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 10,
        "Mar_Imp": 10,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD05",
        "horas_ud": 15,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 4,
        "Mar_Imp": 4,
        "Abr_Prv": 11,
        "Abr_Imp": 11,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD06",
        "horas_ud": 10,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 3,
        "Abr_Imp": 3,
        "May_Prv": 7,
        "May_Imp": 4,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD07",
        "horas_ud": 10,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 9,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD08",
        "horas_ud": 10,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD09",
        "horas_ud": 15,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD10",
        "horas_ud": 10,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      },
      {
        "id_ud": "UD11",
        "horas_ud": 15,
        "Sep_Prv": 0,
        "Sep_Imp": 0,
        "Oct_Prv": 0,
        "Oct_Imp": 0,
        "Nov_Prv": 0,
        "Nov_Imp": 0,
        "Dic_Prv": 0,
        "Dic_Imp": 0,
        "Ene_Prv": 0,
        "Ene_Imp": 0,
        "Feb_Prv": 0,
        "Feb_Imp": 0,
        "Mar_Prv": 0,
        "Mar_Imp": 0,
        "Abr_Prv": 0,
        "Abr_Imp": 0,
        "May_Prv": 0,
        "May_Imp": 0,
        "Jun_Prv": 0,
        "Jun_Imp": 0,
        "Total_Imp": 0
      }
    ],
    "daily_ledger": {
      "01/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "02/10/2025": {
        "sin_docencia": true,
        "seguimiento": ""
      },
      "06/10/2025": {
        "sin_docencia": false,
        "seguimiento": "Clase normal"
      },
      "07/10/2025": {
        "sin_docencia": false,
        "seguimiento": "ddd"
      },
      "08/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "09/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "14/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "15/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "16/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "20/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "21/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "22/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "23/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "27/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "28/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "29/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      },
      "30/10/2025": {
        "sin_docencia": false,
        "seguimiento": ""
      }
    },
    "profesional_ledger": {
      "AN01": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Muy hábil con las manos. Buen trabajo en prácticas de cableado.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-11-15",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Omar quiere trabajar nada más terminar el ciclo. Se orienta hacia empresas de instalaciones locales."
      },
      "AN02": {
        "motivo_eleccion": "Vocación",
        "via_acceso": "Bachillerato",
        "ciclo_previo": "Bachillerato Tecnológico",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Analítica",
        "area_interes": "Ciberseguridad",
        "entorno_laboral_preferido": "Empresa grande",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Valentina destaca en las prácticas de redes y seguridad. Mucha capacidad de análisis.",
        "intencion_al_terminar": "Ciclo superior",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "ASIR o Ciberseguridad GS",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "X",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-10-20",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Valentina tiene muy claro que quiere seguir estudiando. Se le ha informado de los accesos a ASIR y al grado universitario en Ingeniería."
      },
      "AN03": {
        "motivo_eleccion": "Reorientación",
        "via_acceso": "FPGM",
        "ciclo_previo": "SMR (Sistemas Microinformáticos y Redes)",
        "primera_opcion": "X",
        "estudia_y_trabaja": "X",
        "cambio_de_ciclo": "X",
        "experiencia_previa": "Relacionada",
        "sector_experiencia": "Telecomunicaciones / redes",
        "meses_experiencia": "18",
        "jornada_actual": "Parcial",
        "empresa_actual": "Embou",
        "cotiza_seguridad_social": "X",
        "aptitud_principal": "Técnica",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "Empresa grande",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Alba es la más veterana del grupo. Gran autonomía. Referente para sus compañeros.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "Embou o Telefónica",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "X",
        "estado_insercion": "Empleado empresa",
        "relacion_ciclo": "Sí, directamente",
        "empresa_insercion": "Embou",
        "puesto_obtenido": "Técnico de redes",
        "modalidad_contrato": "Temporal",
        "valoracion_egresado": "5",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-09-10",
        "familia_informada": "",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Ya trabaja. Solo necesita el título. Muy buen perfil profesional."
      },
      "AN04": {
        "motivo_eleccion": "Por descarte",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Electrónica / hardware",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "David tiene habilidad práctica pero poca motivación inicial. Ha mejorado con los proyectos.",
        "intencion_al_terminar": "Sin decidir",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-05",
        "familia_informada": "X",
        "derivado_orientador": "X",
        "fecha_derivacion": "2025-11-10",
        "informe_emitido": "",
        "resumen_orientacion": "Se ha derivado al orientador para clarificar motivación. La familia está implicada."
      },
      "AN05": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "X",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Esporádica",
        "sector_experiencia": "Hostelería",
        "meses_experiencia": "6",
        "jornada_actual": "Parcial",
        "empresa_actual": "Restaurante familiar",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Relacional",
        "area_interes": "Atención al cliente",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "idioma_frances": "",
        "obs_aptitudes": "Youssef tiene mucha facilidad para el trato con clientes. Buen perfil para soporte técnico presencial.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-10-15",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Quiere trabajar cuanto antes. Se orienta hacia soporte técnico o instalaciones residenciales."
      },
      "AN06": {
        "motivo_eleccion": "Familia",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Comunicativa",
        "area_interes": "Diseño / UX",
        "entorno_laboral_preferido": "Startup",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "idioma_frances": "X",
        "obs_aptitudes": "Fátima tiene un perfil más creativo que técnico. Destaca en presentaciones y documentación.",
        "intencion_al_terminar": "Ciclo superior",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "DAW o Diseño de interfaces",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "X",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-20",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Se orienta hacia el diseño digital. Candidata para Erasmus+."
      },
      "AN07": {
        "motivo_eleccion": "Reorientación",
        "via_acceso": "Prueba acceso",
        "ciclo_previo": "Cursó 1º Bach sin terminar",
        "primera_opcion": "",
        "estudia_y_trabaja": "X",
        "cambio_de_ciclo": "",
        "experiencia_previa": "No relacionada",
        "sector_experiencia": "Logística",
        "meses_experiencia": "12",
        "jornada_actual": "Parcial",
        "empresa_actual": "Amazon PLAZA",
        "cotiza_seguridad_social": "X",
        "aptitud_principal": "Organizativa",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "Empresa grande",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Daniel combina trabajo y estudios con disciplina. Muy organizado. Conoce bien el entorno logístico.",
        "intencion_al_terminar": "FEOE / prácticas empresa",
        "empresa_objetivo": "Amazon o empresa logística con departamento TI",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "X",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-10-05",
        "familia_informada": "",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Perfil maduro. Quiere aprovechar el FEOE en Amazon o empresa logística grande."
      },
      "AN08": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Emprendedora",
        "area_interes": "Desarrollo software",
        "entorno_laboral_preferido": "Startup",
        "preferencia_geografica": "Internacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "idioma_aleman": "X",
        "obs_aptitudes": "Mario tiene muchas ideas. Siempre propone proyectos extra. Perfil emprendedor muy marcado.",
        "intencion_al_terminar": "Emprender",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "Podría hacer DAM de forma paralela",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "X",
        "interes_emprender": "X",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-10",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Mario quiere montar su propia empresa de soluciones TI. Se le ha orientado hacia Erasmus+ y programas de emprendimiento."
      },
      "AN09": {
        "motivo_eleccion": "Por descarte",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Electrónica / hardware",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Alejandro es tranquilo y metódico. Buen perfil para mantenimiento. Mejoró mucho en el 2T.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-10-30",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Se orienta a empleo local en empresa de mantenimiento o instalaciones."
      },
      "AN11": {
        "motivo_eleccion": "Vocación",
        "via_acceso": "FPGM",
        "ciclo_previo": "SMR",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Relacionada",
        "sector_experiencia": "Informática / redes",
        "meses_experiencia": "3",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Analítica",
        "area_interes": "Ciberseguridad",
        "entorno_laboral_preferido": "Administración pública",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "idioma_rumano": "X",
        "obs_aptitudes": "Elena es la mejor alumna del grupo. Sistemática, rigurosa. Aspiraciones muy altas.",
        "intencion_al_terminar": "Universidad",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "Ingeniería de Telecomunicaciones o Informática",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "X",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "3",
        "fecha_ultima_reunion": "2025-11-25",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "X",
        "resumen_orientacion": "Elena tiene perfil universitario claro. Se le ha orientado hacia el acceso a universidad desde FP GS."
      },
      "AN13": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Lucía es metódica y trabajadora. Buenas prácticas de instalación.",
        "intencion_al_terminar": "FEOE / prácticas empresa",
        "empresa_objetivo": "Levitec o empresa instaladora",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "X",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-11-08",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Quiere hacer el FEOE en empresa local de instalaciones. Tiene empresa identificada."
      },
      "AN14": {
        "motivo_eleccion": "Familia",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Electrónica / hardware",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Hugo viene por tradición familiar (el padre es electricista). Mucha motivación práctica.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "Empresa del padre",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "",
        "interes_emprender": "X",
        "interes_universidad": "",
        "empresa_identificada": "X",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-10-12",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Hugo continuará en el negocio familiar. Se orienta hacia emprendimiento y titulación de instalador."
      },
      "AN15": {
        "motivo_eleccion": "Por descarte",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "X",
        "cambio_de_ciclo": "",
        "experiencia_previa": "No relacionada",
        "sector_experiencia": "Comercio / reparto",
        "meses_experiencia": "8",
        "jornada_actual": "Parcial",
        "empresa_actual": "Glovo",
        "cotiza_seguridad_social": "X",
        "aptitud_principal": "Relacional",
        "area_interes": "Atención al cliente",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Diego tiene mucha calle. Buen trato. Dificultades en la parte más teórica.",
        "intencion_al_terminar": "Sin decidir",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-18",
        "familia_informada": "X",
        "derivado_orientador": "X",
        "fecha_derivacion": "2025-11-20",
        "informe_emitido": "",
        "resumen_orientacion": "Derivado al orientador. Necesita reflexión sobre su futuro profesional."
      },
      "AN16": {
        "motivo_eleccion": "Vocación",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Analítica",
        "area_interes": "Datos / IA",
        "entorno_laboral_preferido": "Empresa grande",
        "preferencia_geografica": "Internacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "idioma_frances": "X",
        "obs_aptitudes": "Laura tiene perfil STEM muy marcado. Le apasionan los datos y la inteligencia artificial.",
        "intencion_al_terminar": "Universidad",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "Doble grado Matemáticas + Informática",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "X",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-22",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "X",
        "resumen_orientacion": "Laura tiene muy claro que irá a la universidad. Se orienta hacia el acceso desde FP."
      },
      "AN17": {
        "motivo_eleccion": "Reorientación",
        "via_acceso": "Convalidación parcial",
        "ciclo_previo": "1 año de Ingeniería Telemática (abandonó)",
        "primera_opcion": "",
        "estudia_y_trabaja": "X",
        "cambio_de_ciclo": "X",
        "experiencia_previa": "Relacionada",
        "sector_experiencia": "Redes / telecomunicaciones",
        "meses_experiencia": "24",
        "jornada_actual": "Parcial",
        "empresa_actual": "Freelance instalaciones hogar",
        "cotiza_seguridad_social": "X",
        "aptitud_principal": "Emprendedora",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "Autónomo / freelance",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Sofía lleva ya 2 años trabajando por cuenta propia. Muy autónoma. El ciclo le da el marco legal.",
        "intencion_al_terminar": "Emprender",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "",
        "interes_emprender": "X",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "Autoempleo",
        "relacion_ciclo": "Sí, directamente",
        "empresa_insercion": "Autónoma",
        "puesto_obtenido": "Instaladora autónoma (hogar y oficinas)",
        "modalidad_contrato": "Autónomo",
        "valoracion_egresado": "4",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-09-15",
        "familia_informada": "",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Sofía ya está insertada como autónoma. El ciclo la regulariza y le da credencial."
      },
      "AN18": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Electrónica / hardware",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Vlad tiene buena base técnica. Trabaja bien en equipo. Algo tímido en las exposiciones.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-11-02",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Vlad está interesado en movilidad Erasmus+. Se le ha informado de las convocatorias."
      },
      "AN19": {
        "motivo_eleccion": "Coste económico",
        "via_acceso": "Bachillerato",
        "ciclo_previo": "Bachillerato Científico",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Analítica",
        "area_interes": "Datos / IA",
        "entorno_laboral_preferido": "Empresa grande",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Carlos eligió FP por economía, pero tiene perfil universitario. Muy buen rendimiento.",
        "intencion_al_terminar": "Universidad",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "Ingeniería Informática (acceso desde FP)",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "X",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-12",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "X",
        "resumen_orientacion": "Se orienta hacia la universidad. Se le ha explicado el acceso con nota FP."
      },
      "AN20": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Andrei es trabajador y constante. Sin grandes aspiraciones declaradas, pero buen técnico.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-10-28",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Se orienta hacia empleo local en instalaciones o mantenimiento."
      },
      "AN21": {
        "motivo_eleccion": "Reorientación",
        "via_acceso": "Prueba acceso",
        "ciclo_previo": "Trabajó 4 años en administración",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "No relacionada",
        "sector_experiencia": "Administración de empresas",
        "meses_experiencia": "48",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Organizativa",
        "area_interes": "Gestión / administración",
        "entorno_laboral_preferido": "Administración pública",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "idioma_frances": "X",
        "obs_aptitudes": "Paula es madura, ordenada y metódica. Su experiencia en administración es un valor añadido.",
        "intencion_al_terminar": "FEOE / prácticas empresa",
        "empresa_objetivo": "Empresa o entidad pública",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-16",
        "familia_informada": "",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Paula busca el sector público. Se le ha informado de bolsas de empleo de Ayuntamientos y DGA."
      },
      "AN22": {
        "motivo_eleccion": "Por descarte",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Electrónica / hardware",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Marcos es hábil con las manos pero le cuesta la teoría. Motivación irregular.",
        "intencion_al_terminar": "Sin decidir",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-11-04",
        "familia_informada": "X",
        "derivado_orientador": "X",
        "fecha_derivacion": "2025-11-06",
        "informe_emitido": "",
        "resumen_orientacion": "Derivado al orientador por falta de motivación. Pendiente de seguimiento."
      },
      "AN23": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "X",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Esporádica",
        "sector_experiencia": "Construcción (ayudante electricista)",
        "meses_experiencia": "10",
        "jornada_actual": "Parcial",
        "empresa_actual": "Empresa familiar de obra",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Técnica",
        "area_interes": "Sistemas / infraestructura",
        "entorno_laboral_preferido": "PYME",
        "preferencia_geografica": "Local / ciudad actual",
        "idioma_espanol": "X",
        "idioma_ingles": "",
        "obs_aptitudes": "Pablo tiene experiencia en obra. Muy práctico. Le falta consolidar la parte teórica.",
        "intencion_al_terminar": "Empleo inmediato",
        "empresa_objetivo": "Empresa instaladora",
        "ciclo_superior_interes": "",
        "interes_erasmus": "",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "",
        "interes_emprender": "X",
        "interes_universidad": "",
        "empresa_identificada": "X",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "1",
        "fecha_ultima_reunion": "2025-10-20",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Pablo se orientará hacia instalaciones o montará su propia empresa en el futuro."
      },
      "AN24": {
        "motivo_eleccion": "Vocación",
        "via_acceso": "ESO",
        "ciclo_previo": "",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Creativa",
        "area_interes": "Diseño / UX",
        "entorno_laboral_preferido": "Startup",
        "preferencia_geografica": "Internacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Mateo tiene perfil muy creativo. Diseña interfaces para las prácticas. Le apasiona la experiencia de usuario.",
        "intencion_al_terminar": "Ciclo superior",
        "empresa_objetivo": "",
        "ciclo_superior_interes": "DAW o Diseño gráfico",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "",
        "interes_mentoria": "X",
        "interes_emprender": "X",
        "interes_universidad": "",
        "empresa_identificada": "",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-19",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Mateo combina tecnología y creatividad. Se orienta hacia DAW o diseño UX."
      },
      "AN25": {
        "motivo_eleccion": "Salida laboral",
        "via_acceso": "Bachillerato",
        "ciclo_previo": "Bachillerato Tecnológico",
        "primera_opcion": "X",
        "estudia_y_trabaja": "",
        "cambio_de_ciclo": "",
        "experiencia_previa": "Sin experiencia",
        "sector_experiencia": "",
        "meses_experiencia": "0",
        "jornada_actual": "No trabaja",
        "empresa_actual": "",
        "cotiza_seguridad_social": "",
        "aptitud_principal": "Analítica",
        "area_interes": "Ciberseguridad",
        "entorno_laboral_preferido": "Empresa grande",
        "preferencia_geografica": "Nacional",
        "idioma_espanol": "X",
        "idioma_ingles": "X",
        "obs_aptitudes": "Sergio destaca en las prácticas de seguridad y redes. Alto rendimiento sostenido.",
        "intencion_al_terminar": "FEOE / prácticas empresa",
        "empresa_objetivo": "Amazon AWS o empresa de ciberseguridad",
        "ciclo_superior_interes": "",
        "interes_erasmus": "X",
        "interes_bolsa_empleo": "X",
        "interes_mentoria": "X",
        "interes_emprender": "",
        "interes_universidad": "",
        "empresa_identificada": "X",
        "estado_insercion": "En formación",
        "relacion_ciclo": "N/A",
        "reuniones_celebradas": "2",
        "fecha_ultima_reunion": "2025-11-21",
        "familia_informada": "X",
        "derivado_orientador": "",
        "informe_emitido": "",
        "resumen_orientacion": "Sergio tiene muy buen perfil. Se orienta hacia FEOE en empresa tecnológica grande o ciberseguridad."
      }
    },
    "tutoria_ledger": {
      "AN01": {
        "SEXO": "H",
        "ORIGEN FAMILIAR. Nacionalidad": "Española/Marruecos",
        "REPETICIONES": "0",
        "TOTAL VULNERABILIDAD": "0",
        "REPITE CURSO": "No",
        "MATERIAS PENDIENTES": "0",
        "BECA MATERIALES": "",
        "BECA AMPA MATERIALES BANCO LIBROS": "",
        "BECA ACNEAES": "",
        "BECA GENERAL MEC": "",
        "SOCIOECONÓMICO, SS": "",
        "DIFICULTADES FAMILIARES": "",
        "AUNA, OZANAM, YMCA": "",
        "ACNEAE": "",
        "TIPO": "",
        "OTRAS DIFICULTADES APRENDIZAJE": "",
        "ABSENTISMO": "",
        "ABSENTISMO 10%": "",
        "SALUD": "",
        "ACS": "",
        "Lengua": "",
        "PT": "",
        "AL": "",
        "COMPENSATORIA": "",
        "TDAH_otros": "",
        "Orientacion": "",
        "Refuerzo": "",
        "PROA": "",
        "TOTAL INTERVENCIONES": "0"
      },
      "AN02": {
        "SEXO": "M",
        "ORIGEN FAMILIAR. Nacionalidad": "Española",
        "REPETICIONES": "0",
        "TOTAL VULNERABILIDAD": "0",
        "BECA MATERIALES": "X",
        "BECA ACNEAES": ""
      },
      "AN03": {
        "SEXO": "M",
        "ORIGEN FAMILIAR. Nacionalidad": "Española",
        "REPETICIONES": "2",
        "TOTAL VULNERABILIDAD": "3",
        "REPITE CURSO": "Sí",
        "MATERIAS PENDIENTES": "4",
        "BECA GENERAL MEC": "X",
        "SOCIOECONÓMICO, SS": "X",
        "DIFICULTADES FAMILIARES": "X",
        "ACNEAE": "X",
        "TIPO": "ACNEE",
        "ABSENTISMO": "10%",
        "PT": "X",
        "TOTAL INTERVENCIONES": "3"
      },
      "AN07": {
        "SEXO": "H",
        "ORIGEN FAMILIAR. Nacionalidad": "Española",
        "REPETICIONES": "1",
        "TOTAL VULNERABILIDAD": "2",
        "REPITE CURSO": "Sí",
        "MATERIAS PENDIENTES": "3",
        "BECA MATERIALES": "X",
        "DIFICULTADES FAMILIARES": "X",
        "TIPO": "COMPENSATORIA",
        "COMPENSATORIA": "X",
        "TOTAL INTERVENCIONES": "1"
      }
    },
    "plano_clase": {
      "rows": 5,
      "cols": 6,
      "seats": {
        "0_0": "AN01",
        "0_1": "AN02",
        "0_2": "AN03",
        "1_0": "AN04",
        "1_1": "AN05",
        "1_2": "AN06",
        "2_0": "AN07",
        "2_1": "AN08",
        "2_2": "AN09",
        "3_0": "AN10",
        "3_1": "AN11",
        "3_2": "AN12"
      }
    }
  },
  "0237-ictve-pd": {
    "tipo": "pd",
    "info_modulo": {
      "codigo": "0237",
      "nombre": "Infraestructuras comunes de telecomunicaciones en viviendas y edificios",
      "horas": 167,
      "ciclo": "Técnico en Instalaciones de Telecomunicaciones",
      "nivel": "Grado Medio",
      "familia": "Electricidad y Electrónica",
      "curso": "1º",
      "profesor": "Equipo Docente"
    },
    "config_contexto": {
      "curso_escolar": "2025-2026",
      "grupo": "1º I.T.",
      "aula": "Taller 3",
      "centro": "IES San Martín"
    },
    "config_aula": {
      "Metodologia": "Aprendizaje basado en proyectos con actividades prácticas en taller y aula virtual. Se combinan exposiciones teóricas con montajes prácticos en maquetas de viviendas.",
      "Atencion a la diversidad": "Adaptaciones curriculares no significativas, refuerzos en horas de tutoría, materiales complementarios en formato digital, actividades de ampliación para alumnado con ritmo más avanzado."
    },
    "horario": {
      "lunes": "08:30-10:30",
      "martes": "11:00-12:00",
      "miercoles": "12:30-13:30",
      "jueves": "",
      "viernes": "09:30-10:30"
    },
    "info_fechas": {
      "inicio": "15/09/2025",
      "fin": "22/06/2026",
      "evaluacion_1": "18/12/2025",
      "evaluacion_2": "25/03/2026",
      "evaluacion_final": "18/06/2026"
    },
    "df_ra": [
      { "id_ra": "RA01", "desc_ra": "Identifica los elementos de las instalaciones de telecomunicaciones en viviendas y edificios, reconociendo su funcionalidad y características técnicas.", "peso_ra": 15, "is_dual": "No" },
      { "id_ra": "RA02", "desc_ra": "Configura pequeñas instalaciones de infraestructuras comunes de telecomunicaciones, realizando los cálculos y ajustes necesarios.", "peso_ra": 20, "is_dual": "No" },
      { "id_ra": "RA03", "desc_ra": "Monta instalaciones de infraestructuras comunes de telecomunicaciones, interpretando planos y esquemas.", "peso_ra": 25, "is_dual": "Sí" },
      { "id_ra": "RA04", "desc_ra": "Verifica el funcionamiento de las instalaciones de telecomunicaciones, realizando las pruebas y mediciones reglamentarias.", "peso_ra": 15, "is_dual": "No" },
      { "id_ra": "RA05", "desc_ra": "Mantiene y repara instalaciones de telecomunicaciones, diagnosticando averías y aplicando técnicas de mantenimiento.", "peso_ra": 15, "is_dual": "Sí" },
      { "id_ra": "RA06", "desc_ra": "Cumple las normas de prevención de riesgos laborales y protección ambiental, evaluando los riesgos asociados.", "peso_ra": 10, "is_dual": "No" }
    ],
    "df_ce": [
      { "id_ce": "CE01", "id_ra": "RA01", "id_ud": "UD01", "desc_ce": "Se han identificado los elementos que componen la ICT de una vivienda o edificio.", "peso_ce": 25 },
      { "id_ce": "CE02", "id_ra": "RA01", "id_ud": "UD01", "desc_ce": "Se ha descrito la funcionalidad de cada elemento de la instalación.", "peso_ce": 25 },
      { "id_ce": "CE03", "id_ra": "RA01", "id_ud": "UD01", "desc_ce": "Se han reconocido las características técnicas de los equipos y materiales.", "peso_ce": 25 },
      { "id_ce": "CE04", "id_ra": "RA01", "id_ud": "UD02", "desc_ce": "Se ha interpretado la normativa vigente aplicable a las ICT.", "peso_ce": 25 },
      { "id_ce": "CE05", "id_ra": "RA02", "id_ud": "UD02", "desc_ce": "Se han seleccionado los equipos y materiales adecuados para cada instalación.", "peso_ce": 30 },
      { "id_ce": "CE06", "id_ra": "RA02", "id_ud": "UD02", "desc_ce": "Se han realizado los cálculos necesarios para la configuración de la instalación.", "peso_ce": 35 },
      { "id_ce": "CE07", "id_ra": "RA02", "id_ud": "UD03", "desc_ce": "Se han elaborado esquemas y croquis de la instalación.", "peso_ce": 35 },
      { "id_ce": "CE08", "id_ra": "RA03", "id_ud": "UD03", "desc_ce": "Se han interpretado planos técnicos de instalaciones de telecomunicaciones.", "peso_ce": 20 },
      { "id_ce": "CE09", "id_ra": "RA03", "id_ud": "UD03", "desc_ce": "Se han montado los elementos de la instalación siguiendo las especificaciones técnicas.", "peso_ce": 30 },
      { "id_ce": "CE10", "id_ra": "RA03", "id_ud": "UD04", "desc_ce": "Se han realizado las conexiones entre equipos siguiendo los esquemas.", "peso_ce": 25 },
      { "id_ce": "CE11", "id_ra": "RA03", "id_ud": "UD04", "desc_ce": "Se han aplicado las técnicas de montaje y fijación adecuadas.", "peso_ce": 25 },
      { "id_ce": "CE12", "id_ra": "RA04", "id_ud": "UD05", "desc_ce": "Se han realizado las pruebas funcionales de la instalación.", "peso_ce": 30 },
      { "id_ce": "CE13", "id_ra": "RA04", "id_ud": "UD05", "desc_ce": "Se han efectuado las mediciones reglamentarias con los instrumentos adecuados.", "peso_ce": 35 },
      { "id_ce": "CE14", "id_ra": "RA04", "id_ud": "UD05", "desc_ce": "Se ha verificado el cumplimiento de la normativa vigente.", "peso_ce": 35 },
      { "id_ce": "CE15", "id_ra": "RA05", "id_ud": "UD06", "desc_ce": "Se han diagnosticado averías típicas en instalaciones de ICT.", "peso_ce": 35 },
      { "id_ce": "CE16", "id_ra": "RA05", "id_ud": "UD06", "desc_ce": "Se han aplicado técnicas de mantenimiento preventivo.", "peso_ce": 30 },
      { "id_ce": "CE17", "id_ra": "RA05", "id_ud": "UD06", "desc_ce": "Se han reparado las averías detectadas utilizando las herramientas adecuadas.", "peso_ce": 35 },
      { "id_ce": "CE18", "id_ra": "RA06", "id_ud": "UD01", "desc_ce": "Se han identificado los riesgos laborales asociados a las instalaciones de ICT.", "peso_ce": 30 },
      { "id_ce": "CE19", "id_ra": "RA06", "id_ud": "UD01", "desc_ce": "Se han aplicado las medidas de prevención y protección adecuadas.", "peso_ce": 35 },
      { "id_ce": "CE20", "id_ra": "RA06", "id_ud": "UD01", "desc_ce": "Se ha cumplido la normativa de protección ambiental en la gestión de residuos.", "peso_ce": 35 }
    ],
    "df_ud": [
      { "id_ud": "UD01", "desc_ud": "ICT en viviendas y edificios: elementos, normativa y diseño", "horas_ud": 30, "ra_mappings": { "RA01": "RA01", "RA06": "RA06" }, "RA01": 50, "RA02": 0, "RA03": 0, "RA04": 0, "RA05": 0, "RA06": 100 },
      { "id_ud": "UD02", "desc_ud": "Instalaciones de antenas y televisión satélite", "horas_ud": 30, "ra_mappings": { "RA01": "RA01", "RA02": "RA02" }, "RA01": 30, "RA02": 40, "RA03": 0, "RA04": 0, "RA05": 0, "RA06": 0 },
      { "id_ud": "UD03", "desc_ud": "Infraestructuras de telecomunicaciones de banda ancha", "horas_ud": 28, "ra_mappings": { "RA02": "RA02", "RA03": "RA03" }, "RA01": 20, "RA02": 40, "RA03": 30, "RA04": 0, "RA05": 0, "RA06": 0 },
      { "id_ud": "UD04", "desc_ud": "Instalaciones de telefonía y redes de datos", "horas_ud": 30, "ra_mappings": { "RA03": "RA03" }, "RA01": 0, "RA02": 20, "RA03": 40, "RA04": 0, "RA05": 0, "RA06": 0 },
      { "id_ud": "UD05", "desc_ud": "Seguridad y verificación de instalaciones de telecomunicaciones", "horas_ud": 25, "ra_mappings": { "RA04": "RA04" }, "RA01": 0, "RA02": 0, "RA03": 10, "RA04": 60, "RA05": 0, "RA06": 0 },
      { "id_ud": "UD06", "desc_ud": "Mantenimiento y reparación de instalaciones ICT", "horas_ud": 24, "ra_mappings": { "RA05": "RA05" }, "RA01": 0, "RA02": 0, "RA03": 20, "RA04": 40, "RA05": 100, "RA06": 0 }
    ],
    "df_sesiones": [
      { "ID": "S001", "id_ud": "UD01", "Num_Orden": 1, "Horas": 2, "Tipo_Actividad": "Teoría", "RA_CE": "RA01 / CE01-CE02", "Contenidos": "Introducción a las ICT. Elementos básicos de una instalación.", "Aspectos_Clave": "Identificar los componentes principales", "Recursos": "Presentación digital, muestras físicas de materiales" },
      { "ID": "S002", "id_ud": "UD01", "Num_Orden": 2, "Horas": 2, "Tipo_Actividad": "Práctica", "RA_CE": "RA01 / CE03", "Contenidos": "Reconocimiento de materiales y equipos en maqueta didáctica.", "Aspectos_Clave": "Manipulación correcta de materiales", "Recursos": "Maqueta didáctica, catálogos técnicos" },
      { "ID": "S003", "id_ud": "UD01", "Num_Orden": 3, "Horas": 2, "Tipo_Actividad": "Teoría", "RA_CE": "RA01 / CE04", "Contenidos": "Normativa ICT: Real Decreto 346/2011, UNE 133100.", "Aspectos_Clave": "Interpretación de normativa", "Recursos": "Documentación normativa, esquemas" },
      { "ID": "S004", "id_ud": "UD02", "Num_Orden": 4, "Horas": 2, "Tipo_Actividad": "Teoría", "RA_CE": "RA01 / CE01-CE02", "Contenidos": "Instalaciones de antenas: tipos, elementos, características.", "Aspectos_Clave": "Comprensión del sistema de antenas", "Recursos": "Esquemas, vídeos demostrativos" },
      { "ID": "S005", "id_ud": "UD02", "Num_Orden": 5, "Horas": 2, "Tipo_Actividad": "Práctica", "RA_CE": "RA02 / CE05-CE06", "Contenidos": "Cálculo de instalaciones de antenas: niveles de señal, pérdidas.", "Aspectos_Clave": "Realizar cálculos correctamente", "Recursos": "Calculadora, tablas de datos, software de simulación" },
      { "ID": "S006", "id_ud": "UD02", "Num_Orden": 6, "Horas": 2, "Tipo_Actividad": "Taller", "RA_CE": "RA02 / CE07", "Contenidos": "Montaje de antena parabólica y soporte.", "Aspectos_Clave": "Orientación y fijación correcta", "Recursos": "Antena parabólica, soporte, herramientas" },
      { "ID": "S007", "id_ud": "UD03", "Num_Orden": 7, "Horas": 2, "Tipo_Actividad": "Teoría", "RA_CE": "RA02 / CE05", "Contenidos": "Infraestructuras de banda ancha: fibra óptica, cable coaxial, par trenzado.", "Aspectos_Clave": "Diferencias entre medios de transmisión", "Recursos": "Muestras de cables, presentación" },
      { "ID": "S008", "id_ud": "UD03", "Num_Orden": 8, "Horas": 2, "Tipo_Actividad": "Práctica", "RA_CE": "RA02 / CE06-CE07", "Contenidos": "Elaboración de esquemas de instalación de banda ancha.", "Aspectos_Clave": "Cumplir simbología normalizada", "Recursos": "Software de diseño, plantillas" },
      { "ID": "S009", "id_ud": "UD03", "Num_Orden": 9, "Horas": 2, "Tipo_Actividad": "Taller", "RA_CE": "RA03 / CE08-CE09", "Contenidos": "Montaje de toma de fibra óptica y cableado interior.", "Aspectos_Clave": "Técnicas de conexión y fijación", "Recursos": "Fibra óptica, conectorizadora, herramientas" },
      { "ID": "S010", "id_ud": "UD04", "Num_Orden": 10, "Horas": 2, "Tipo_Actividad": "Teoría", "RA_CE": "RA03 / CE10", "Contenidos": "Instalaciones de telefonía: centralización, distribución, puntos de acceso.", "Aspectos_Clave": "Arquitectura de la red telefónica", "Recursos": "Planos, esquemas" },
      { "ID": "S011", "id_ud": "UD04", "Num_Orden": 11, "Horas": 2, "Tipo_Actividad": "Taller", "RA_CE": "RA03 / CE10-CE11", "Contenidos": "Montaje de rosetas telefónicas y conexionado de red de datos.", "Aspectos_Clave": "Conexionado correcto según norma", "Recursos": "Rosetas, cable FTP, crimpadora, comprobador" },
      { "ID": "S012", "id_ud": "UD05", "Num_Orden": 12, "Horas": 2, "Tipo_Actividad": "Práctica", "RA_CE": "RA04 / CE12-CE13", "Contenidos": "Mediciones en instalaciones: nivel de señal, impedancia, continuidad.", "Aspectos_Clave": "Uso correcto de instrumentos de medida", "Recursos": "Medidor de campo, polímetro, analizador" },
      { "ID": "S013", "id_ud": "UD05", "Num_Orden": 13, "Horas": 2, "Tipo_Actividad": "Teoría", "RA_CE": "RA04 / CE14", "Contenidos": "Verificación reglamentaria de instalaciones. Certificados.", "Aspectos_Clave": "Cumplimiento de normativa", "Recursos": "Modelos de certificados, checklist" },
      { "ID": "S014", "id_ud": "UD06", "Num_Orden": 14, "Horas": 2, "Tipo_Actividad": "Práctica", "RA_CE": "RA05 / CE15-CE16", "Contenidos": "Diagnóstico de averías típicas en ICT.", "Aspectos_Clave": "Método sistemático de diagnóstico", "Recursos": "Maqueta con averías simuladas, documentación técnica" },
      { "ID": "S015", "id_ud": "UD06", "Num_Orden": 15, "Horas": 2, "Tipo_Actividad": "Taller", "RA_CE": "RA05 / CE17", "Contenidos": "Reparación de averías: sustitución de elementos, ajustes.", "Aspectos_Clave": "Técnicas de reparación", "Recursos": "Herramientas, repuestos, maqueta" }
    ],
    "df_tareas": [
      { "ID": "T01", "id_act": "ACT01", "Nombre_Tarea": "Diseño de ICT para vivienda unifamiliar", "Reto": "Diseñar y presupuestar la instalación completa de ICT para una vivienda de 100m²", "RA_Asociados": "RA01, RA02", "Instrumento": "Rúbrica de proyecto", "desc_act": "Los alumnos deberán diseñar la ICT completa de una vivienda unifamiliar, incluyendo antenas, telefonía y banda ancha, elaborando planos, lista de materiales y presupuesto." },
      { "ID": "T02", "id_act": "ACT02", "Nombre_Tarea": "Montaje de instalación de antena colectiva", "Reto": "Montar y poner en marcha una instalación de antena colectiva para 4 viviendas", "RA_Asociados": "RA03", "Instrumento": "Lista de verificación", "desc_act": "Montaje de una instalación de antena colectiva con amplificador, derivadores y tomas, siguiendo el esquema proporcionado." },
      { "ID": "T03", "id_act": "ACT03", "Nombre_Tarea": "Verificación y medidas de instalación ICT", "Reto": "Realizar el informe de verificación de una instalación ICT existente", "RA_Asociados": "RA04", "Instrumento": "Informe técnico", "desc_act": "Los alumnos realizarán mediciones de nivel de señal, pérdidas y continuidad en una instalación existente, elaborando el informe técnico correspondiente." },
      { "ID": "T04", "id_act": "ACT04", "Nombre_Tarea": "Diagnóstico y reparación de averías en ICT", "Reto": "Diagnosticar y reparar 3 averías simuladas en una instalación ICT", "RA_Asociados": "RA05", "Instrumento": "Rúbrica de práctica", "desc_act": "Los alumnos deberán identificar y reparar averías en una maqueta de ICT, documentando el proceso seguido." },
      { "ID": "T05", "id_act": "ACT05", "Nombre_Tarea": "Evaluación de riesgos en instalaciones ICT", "Reto": "Elaborar un plan de prevención para el montaje de una ICT", "RA_Asociados": "RA06", "Instrumento": "Checklist de PRL", "desc_act": "Identificar los riesgos laborales asociados al montaje de ICT y proponer medidas preventivas." }
    ],
    "df_act": [],
    "df_instr": [],
    "df_pr": [],
    "df_dua": [],
    "df_contingencia": [],
    "df_ace": [],
    "calendar_notes": {
      "f_2025-10-12": "Fiesta Nacional de España",
      "f_2025-11-01": "Todos los Santos",
      "f_2025-12-06": "Día de la Constitución",
      "f_2025-12-08": "Inmaculada Concepción",
      "f_2025-12-22": "Inicio vacaciones Navidad",
      "f_2026-01-07": "Fin vacaciones Navidad",
      "f_2026-03-30": "Inicio vacaciones Semana Santa",
      "f_2026-04-06": "Fin vacaciones Semana Santa",
      "f_2026-05-01": "Día del Trabajo",
      "r_2025-12-17": "1ª Evaluación",
      "r_2026-03-24": "2ª Evaluación",
      "r_2026-06-17": "Evaluación Final"
    },
    "planning_ledger": {
      "2025-09-15": ["UD01"],
      "2025-09-22": ["UD01"],
      "2025-09-29": ["UD01"],
      "2025-10-06": ["UD02"],
      "2025-10-20": ["UD02"],
      "2025-10-27": ["UD02"],
      "2025-11-03": ["UD03"],
      "2025-11-10": ["UD03"],
      "2025-11-17": ["UD03"],
      "2025-11-24": ["UD04"],
      "2025-12-01": ["UD04"],
      "2025-12-15": ["UD04"],
      "2026-01-12": ["UD05"],
      "2026-01-19": ["UD05"],
      "2026-01-26": ["UD06"],
      "2026-02-02": ["UD06"]
    }
  }
};
