"""add_degree_code

Revision ID: 15cea7c181c0
Revises: ca0dfb195124
Create Date: 2026-06-02 18:41:18.064366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cea7c181c0'
down_revision: Union[str, Sequence[str], None] = 'ca0dfb195124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degrees', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_degrees_code'), 'degrees', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_degrees_code'), table_name='degrees')
    op.drop_column('degrees', 'code')
    # ### end Alembic commands ###
