"""add_boa_articles_to_degree

Revision ID: 9ecd0268c8c7
Revises: 15cea7c181c0
Create Date: 2026-06-03 15:28:03.337710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecd0268c8c7'
down_revision: Union[str, Sequence[str], None] = '15cea7c181c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degrees', sa.Column('boa_articles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('degrees', 'boa_articles')
    # ### end Alembic commands ###
