"""initial_schema

Revision ID: ca0dfb195124
Revises: 
Create Date: 2026-06-02 16:07:11.974400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0dfb195124'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=False)
    op.create_table('module_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['module_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_documents_id'), 'module_documents', ['id'], unique=False)
    op.create_table('professional_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_families_code'), 'professional_families', ['code'], unique=True)
    op.create_index(op.f('ix_professional_families_id'), 'professional_families', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ace_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ace_items_id'), 'ace_items', ['id'], unique=False)
    op.create_index(op.f('ix_ace_items_item_id'), 'ace_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_ace_items_module_document_id'), 'ace_items', ['module_document_id'], unique=False)
    op.create_table('activity_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('id_act', sa.String(), nullable=True),
    sa.Column('desc_act', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('tri_act', sa.String(), nullable=True),
    sa.Column('peso_act', sa.String(), nullable=True),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_items_id'), 'activity_items', ['id'], unique=False)
    op.create_index(op.f('ix_activity_items_id_act'), 'activity_items', ['id_act'], unique=False)
    op.create_index(op.f('ix_activity_items_module_document_id'), 'activity_items', ['module_document_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_date_str'), 'attendance_records', ['date_str'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_module_document_id'), 'attendance_records', ['module_document_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('calendar_note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('note_key', sa.String(), nullable=True),
    sa.Column('note_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_note_items_id'), 'calendar_note_items', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_note_items_module_document_id'), 'calendar_note_items', ['module_document_id'], unique=False)
    op.create_index(op.f('ix_calendar_note_items_note_key'), 'calendar_note_items', ['note_key'], unique=False)
    op.create_table('config_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_document_id')
    )
    op.create_index(op.f('ix_config_dates_id'), 'config_dates', ['id'], unique=False)
    op.create_table('contingency_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('escenario', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contingency_items_id'), 'contingency_items', ['id'], unique=False)
    op.create_index(op.f('ix_contingency_items_item_id'), 'contingency_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_contingency_items_module_document_id'), 'contingency_items', ['module_document_id'], unique=False)
    op.create_table('course_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('apellidos', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('edad', sa.String(), nullable=True),
    sa.Column('nacimiento', sa.String(), nullable=True),
    sa.Column('repite', sa.String(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('movil', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_students_id'), 'course_students', ['id'], unique=False)
    op.create_index(op.f('ix_course_students_module_document_id'), 'course_students', ['module_document_id'], unique=False)
    op.create_index(op.f('ix_course_students_student_id'), 'course_students', ['student_id'], unique=False)
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('BASICA', 'MEDIO', 'SUPERIOR', 'ESPECIALIZACION', name='nivelfp'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['professional_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_degrees_id'), 'degrees', ['id'], unique=False)
    op.create_table('didactic_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('id_ud', sa.String(), nullable=True),
    sa.Column('desc_ud', sa.String(), nullable=True),
    sa.Column('horas_ud', sa.Integer(), nullable=True),
    sa.Column('ra_mappings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_didactic_units_id'), 'didactic_units', ['id'], unique=False)
    op.create_index(op.f('ix_didactic_units_id_ud'), 'didactic_units', ['id_ud'], unique=False)
    op.create_index(op.f('ix_didactic_units_module_document_id'), 'didactic_units', ['module_document_id'], unique=False)
    op.create_table('dua_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('barrera', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dua_items_id'), 'dua_items', ['id'], unique=False)
    op.create_index(op.f('ix_dua_items_item_id'), 'dua_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_dua_items_module_document_id'), 'dua_items', ['module_document_id'], unique=False)
    op.create_table('evaluation_criterion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('id_ce', sa.String(), nullable=True),
    sa.Column('id_ra', sa.String(), nullable=True),
    sa.Column('id_ud', sa.String(), nullable=True),
    sa.Column('desc_ce', sa.String(), nullable=True),
    sa.Column('peso_ce', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_criterion_items_id'), 'evaluation_criterion_items', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_criterion_items_id_ce'), 'evaluation_criterion_items', ['id_ce'], unique=False)
    op.create_index(op.f('ix_evaluation_criterion_items_id_ra'), 'evaluation_criterion_items', ['id_ra'], unique=False)
    op.create_index(op.f('ix_evaluation_criterion_items_module_document_id'), 'evaluation_criterion_items', ['module_document_id'], unique=False)
    op.create_table('feoe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feoe_items_id'), 'feoe_items', ['id'], unique=False)
    op.create_index(op.f('ix_feoe_items_item_id'), 'feoe_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_feoe_items_module_document_id'), 'feoe_items', ['module_document_id'], unique=False)
    op.create_table('instrument_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('practica', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_items_id'), 'instrument_items', ['id'], unique=False)
    op.create_index(op.f('ix_instrument_items_item_id'), 'instrument_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_instrument_items_module_document_id'), 'instrument_items', ['module_document_id'], unique=False)
    op.create_table('learning_outcome_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('id_ra', sa.String(), nullable=True),
    sa.Column('desc_ra', sa.String(), nullable=True),
    sa.Column('peso_ra', sa.String(), nullable=True),
    sa.Column('is_dual', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcome_items_id'), 'learning_outcome_items', ['id'], unique=False)
    op.create_index(op.f('ix_learning_outcome_items_id_ra'), 'learning_outcome_items', ['id_ra'], unique=False)
    op.create_index(op.f('ix_learning_outcome_items_module_document_id'), 'learning_outcome_items', ['module_document_id'], unique=False)
    op.create_table('module_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_document_id')
    )
    op.create_index(op.f('ix_module_infos_id'), 'module_infos', ['id'], unique=False)
    op.create_table('planning_ledger_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('id_ud', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_ledger_items_date_str'), 'planning_ledger_items', ['date_str'], unique=False)
    op.create_index(op.f('ix_planning_ledger_items_id'), 'planning_ledger_items', ['id'], unique=False)
    op.create_index(op.f('ix_planning_ledger_items_module_document_id'), 'planning_ledger_items', ['module_document_id'], unique=False)
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provinces_id'), 'provinces', ['id'], unique=False)
    op.create_table('schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_items_day_of_week'), 'schedule_items', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_schedule_items_id'), 'schedule_items', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_items_module_document_id'), 'schedule_items', ['module_document_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('id_ud', sa.String(), nullable=True),
    sa.Column('num_orden', sa.Integer(), nullable=True),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('tipo_actividad', sa.String(), nullable=True),
    sa.Column('ra_ce', sa.String(), nullable=True),
    sa.Column('contenidos', sa.String(), nullable=True),
    sa.Column('aspectos_clave', sa.String(), nullable=True),
    sa.Column('recursos', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_id_ud'), 'sessions', ['id_ud'], unique=False)
    op.create_index(op.f('ix_sessions_module_document_id'), 'sessions', ['module_document_id'], unique=False)
    op.create_table('sgmt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('id_ud', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sgmt_items_id'), 'sgmt_items', ['id'], unique=False)
    op.create_index(op.f('ix_sgmt_items_id_ud'), 'sgmt_items', ['id_ud'], unique=False)
    op.create_index(op.f('ix_sgmt_items_module_document_id'), 'sgmt_items', ['module_document_id'], unique=False)
    op.create_table('student_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('eval_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_evaluations_id'), 'student_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_student_evaluations_module_document_id'), 'student_evaluations', ['module_document_id'], unique=False)
    op.create_index(op.f('ix_student_evaluations_student_id'), 'student_evaluations', ['student_id'], unique=False)
    op.create_table('task_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_document_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('nombre_tarea', sa.String(), nullable=True),
    sa.Column('reto', sa.String(), nullable=True),
    sa.Column('ra_asociados', sa.String(), nullable=True),
    sa.Column('instrumento', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_document_id'], ['module_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_items_id'), 'task_items', ['id'], unique=False)
    op.create_index(op.f('ix_task_items_item_id'), 'task_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_task_items_module_document_id'), 'task_items', ['module_document_id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('is_dual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('titularity', sa.Enum('PUBLICA', 'CONCERTADA', 'PRIVADA', name='titularidad'), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centers_code'), 'centers', ['code'], unique=True)
    op.create_index(op.f('ix_centers_id'), 'centers', ['id'], unique=False)
    op.create_table('learning_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('ra_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_id'), 'learning_outcomes', ['id'], unique=False)
    op.create_table('center_degrees',
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ),
    sa.PrimaryKeyConstraint('center_id', 'degree_id')
    )
    op.create_table('center_staff',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('is_center_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'center_id')
    )
    op.create_table('course_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_groups_id'), 'course_groups', ['id'], unique=False)
    op.create_table('department_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['professional_families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_heads_id'), 'department_heads', ['id'], unique=False)
    op.create_table('dual_coordinators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dual_coordinators_id'), 'dual_coordinators', ['id'], unique=False)
    op.create_table('dual_general_tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['professional_families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dual_general_tutors_id'), 'dual_general_tutors', ['id'], unique=False)
    op.create_table('head_of_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_head_of_studies_id'), 'head_of_studies', ['id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('course_group_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['course_group_id'], ['course_groups.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_table('group_tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_group_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('is_dual_tutor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['course_group_id'], ['course_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_tutors_id'), 'group_tutors', ['id'], unique=False)
    op.create_table('teaching_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('course_group_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['course_group_id'], ['course_groups.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_assignments_id'), 'teaching_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_assignments_id'), table_name='teaching_assignments')
    op.drop_table('teaching_assignments')
    op.drop_index(op.f('ix_group_tutors_id'), table_name='group_tutors')
    op.drop_table('group_tutors')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_head_of_studies_id'), table_name='head_of_studies')
    op.drop_table('head_of_studies')
    op.drop_index(op.f('ix_dual_general_tutors_id'), table_name='dual_general_tutors')
    op.drop_table('dual_general_tutors')
    op.drop_index(op.f('ix_dual_coordinators_id'), table_name='dual_coordinators')
    op.drop_table('dual_coordinators')
    op.drop_index(op.f('ix_department_heads_id'), table_name='department_heads')
    op.drop_table('department_heads')
    op.drop_index(op.f('ix_course_groups_id'), table_name='course_groups')
    op.drop_table('course_groups')
    op.drop_table('center_staff')
    op.drop_table('center_degrees')
    op.drop_index(op.f('ix_learning_outcomes_id'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_index(op.f('ix_centers_id'), table_name='centers')
    op.drop_index(op.f('ix_centers_code'), table_name='centers')
    op.drop_table('centers')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_task_items_module_document_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_item_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_id'), table_name='task_items')
    op.drop_table('task_items')
    op.drop_index(op.f('ix_student_evaluations_student_id'), table_name='student_evaluations')
    op.drop_index(op.f('ix_student_evaluations_module_document_id'), table_name='student_evaluations')
    op.drop_index(op.f('ix_student_evaluations_id'), table_name='student_evaluations')
    op.drop_table('student_evaluations')
    op.drop_index(op.f('ix_sgmt_items_module_document_id'), table_name='sgmt_items')
    op.drop_index(op.f('ix_sgmt_items_id_ud'), table_name='sgmt_items')
    op.drop_index(op.f('ix_sgmt_items_id'), table_name='sgmt_items')
    op.drop_table('sgmt_items')
    op.drop_index(op.f('ix_sessions_module_document_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id_ud'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_schedule_items_module_document_id'), table_name='schedule_items')
    op.drop_index(op.f('ix_schedule_items_id'), table_name='schedule_items')
    op.drop_index(op.f('ix_schedule_items_day_of_week'), table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_index(op.f('ix_provinces_id'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_planning_ledger_items_module_document_id'), table_name='planning_ledger_items')
    op.drop_index(op.f('ix_planning_ledger_items_id'), table_name='planning_ledger_items')
    op.drop_index(op.f('ix_planning_ledger_items_date_str'), table_name='planning_ledger_items')
    op.drop_table('planning_ledger_items')
    op.drop_index(op.f('ix_module_infos_id'), table_name='module_infos')
    op.drop_table('module_infos')
    op.drop_index(op.f('ix_learning_outcome_items_module_document_id'), table_name='learning_outcome_items')
    op.drop_index(op.f('ix_learning_outcome_items_id_ra'), table_name='learning_outcome_items')
    op.drop_index(op.f('ix_learning_outcome_items_id'), table_name='learning_outcome_items')
    op.drop_table('learning_outcome_items')
    op.drop_index(op.f('ix_instrument_items_module_document_id'), table_name='instrument_items')
    op.drop_index(op.f('ix_instrument_items_item_id'), table_name='instrument_items')
    op.drop_index(op.f('ix_instrument_items_id'), table_name='instrument_items')
    op.drop_table('instrument_items')
    op.drop_index(op.f('ix_feoe_items_module_document_id'), table_name='feoe_items')
    op.drop_index(op.f('ix_feoe_items_item_id'), table_name='feoe_items')
    op.drop_index(op.f('ix_feoe_items_id'), table_name='feoe_items')
    op.drop_table('feoe_items')
    op.drop_index(op.f('ix_evaluation_criterion_items_module_document_id'), table_name='evaluation_criterion_items')
    op.drop_index(op.f('ix_evaluation_criterion_items_id_ra'), table_name='evaluation_criterion_items')
    op.drop_index(op.f('ix_evaluation_criterion_items_id_ce'), table_name='evaluation_criterion_items')
    op.drop_index(op.f('ix_evaluation_criterion_items_id'), table_name='evaluation_criterion_items')
    op.drop_table('evaluation_criterion_items')
    op.drop_index(op.f('ix_dua_items_module_document_id'), table_name='dua_items')
    op.drop_index(op.f('ix_dua_items_item_id'), table_name='dua_items')
    op.drop_index(op.f('ix_dua_items_id'), table_name='dua_items')
    op.drop_table('dua_items')
    op.drop_index(op.f('ix_didactic_units_module_document_id'), table_name='didactic_units')
    op.drop_index(op.f('ix_didactic_units_id_ud'), table_name='didactic_units')
    op.drop_index(op.f('ix_didactic_units_id'), table_name='didactic_units')
    op.drop_table('didactic_units')
    op.drop_index(op.f('ix_degrees_id'), table_name='degrees')
    op.drop_table('degrees')
    op.drop_index(op.f('ix_course_students_student_id'), table_name='course_students')
    op.drop_index(op.f('ix_course_students_module_document_id'), table_name='course_students')
    op.drop_index(op.f('ix_course_students_id'), table_name='course_students')
    op.drop_table('course_students')
    op.drop_index(op.f('ix_contingency_items_module_document_id'), table_name='contingency_items')
    op.drop_index(op.f('ix_contingency_items_item_id'), table_name='contingency_items')
    op.drop_index(op.f('ix_contingency_items_id'), table_name='contingency_items')
    op.drop_table('contingency_items')
    op.drop_index(op.f('ix_config_dates_id'), table_name='config_dates')
    op.drop_table('config_dates')
    op.drop_index(op.f('ix_calendar_note_items_note_key'), table_name='calendar_note_items')
    op.drop_index(op.f('ix_calendar_note_items_module_document_id'), table_name='calendar_note_items')
    op.drop_index(op.f('ix_calendar_note_items_id'), table_name='calendar_note_items')
    op.drop_table('calendar_note_items')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_module_document_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date_str'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_activity_items_module_document_id'), table_name='activity_items')
    op.drop_index(op.f('ix_activity_items_id_act'), table_name='activity_items')
    op.drop_index(op.f('ix_activity_items_id'), table_name='activity_items')
    op.drop_table('activity_items')
    op.drop_index(op.f('ix_ace_items_module_document_id'), table_name='ace_items')
    op.drop_index(op.f('ix_ace_items_item_id'), table_name='ace_items')
    op.drop_index(op.f('ix_ace_items_id'), table_name='ace_items')
    op.drop_table('ace_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_professional_families_id'), table_name='professional_families')
    op.drop_index(op.f('ix_professional_families_code'), table_name='professional_families')
    op.drop_table('professional_families')
    op.drop_index(op.f('ix_module_documents_id'), table_name='module_documents')
    op.drop_table('module_documents')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
